version: '3.7'
services:
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pinot-advanced
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    depends_on:
      - zookeeper
    networks:
      - pinot-advanced
    healthcheck: {test: nc -z localhost 9092, interval: 1s}
  #node_app:
  #  image: node:latest
  #  volumes:
  #    - ./scripts:/scripts
  #  command: sh -c "npm i eventsource kafkajs && node /scripts/wikievents.js"
  #  working_dir: /scripts
  #  depends_on:
  #    - kafka
  #  networks:
  #    - pinot-advanced
  pinot-controller:
    image: apachepinot/pinot:1.1.0
    command: "StartController -zkAddress zookeeper:2181"
    container_name: "pinot-controller"
    volumes:
      - ./scripts:/scripts
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks:
      - pinot-advanced
  pinot-broker:
    image: apachepinot/pinot:1.1.0
    command: "StartBroker -zkAddress zookeeper:2181"
    restart: unless-stopped
    container_name: "pinot-broker"
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks:
      - pinot-advanced
  pinot-server:
    image: apachepinot/pinot:1.1.0
    command: "StartServer -zkAddress zookeeper:2181"
    restart: unless-stopped
    container_name: "pinot-server"
    depends_on:
      - pinot-broker
    networks:
      - pinot-advanced
  pinot-command-runner:
    image: apachepinot/pinot:1.1.0
    volumes:
      - ./scripts:/scripts
    command: "'./bin/pinot-admin.sh AddTable -schemaFile /scripts/wikipedia_events_schema.json -tableConfigFile /scripts/wikipedia_events_realtime_table_config.json -controllerHost pinot-controller -exec'"
    container_name: "pinot-command-runner"
    restart: on-failure
    entrypoint: "bash -c"
    environment:
    - "JAVA_OPTS=-Dpinot.admin.system.exit=true"
    depends_on:
      - pinot-controller
      - kafka
    networks:
      - pinot-advanced
networks:
  pinot-advanced:
    name: pinot-advanced